apiVersion: v1
kind: Service
metadata:
  name: test
  labels:
    app: rep
spec:
  clusterIP: None
  selector: # It must match the label defined in the StatefulSet
    app: rep # Register pods in DNS
  ports:
    - port: 6000
      name: server-port
      protocol: TCP
      targetPort: 6000
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: raft
spec:
  serviceName: raft-service
  replicas: 3
  podManagementPolicy: Parallel # por defecto sería OrderedReady (secuencial)
  selector:
    matchLabels:
      app: rep # tiene que corresponder a .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: rep
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: servidor
          image: localhost:5001/servidor:latest
          env:
            - name: MISUBDOMINIODNS
              value: raft-service.default.svc.cluster.local
            - name: MINOMBREPOD # primera replica r-0, segunda r-1, etc
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command:
            - srvraft
            - $(MINOMBREPOD)
          ports:
            - containerPort: 6000